env:
  browser: true
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:vue/essential"
  - "plugin:vue/vue3-recommended"
  - "prettier"
  - "prettier/vue"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - vue
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
