---
version: "3.7"
services:
  autosolver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: autosolver:latest
    container_name: autosolver
    ports:
      - "80:80"
    restart: always
