name: Checking Docker Build after push

on:
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Build Prod
      run: ./deploy

